### ISSUE TITLE
Can't login with Crowd user at nexus 3.7.1-02

### ISSUE THREAD

**Issue by dario-rodriguez** [pingunaut/nexus3-crowd-plugin#34] opened 2018-01-17 09:17 UTC
Hello, 

I have installed this plugin in my nexus 3.7.1-02. I have also a Jira 7.6.2 with crowd. 

The problem is when Im try to login at nexus with my Jira user I get this error:

```
nexus3_1 | 2018-01-17 09:14:58,006+0000 INFO  [qtp1698144011-48] *UNKNOWN com.pingunaut.nexus3.crowd.plugin.CrowdAuthenticatingRealm - doGetAuthenticationInfo for darrodri
nexus3_1 | 2018-01-17 09:14:58,030+0000 ERROR [qtp1698144011-48] *UNKNOWN com.pingunaut.nexus3.crowd.plugin.internal.entity.mapper.CrowdMapper - Error with request org.apache.http.client.entity.DecompressingEntity@2428900f - 500
nexus3_1 | 2018-01-17 09:14:58,032+0000 INFO  [qtp1698144011-48] *UNKNOWN com.pingunaut.nexus3.crowd.plugin.CrowdAuthenticatingRealm - crowd authenticated: false
```

But when I try to add a new external role, I can list all Jira groups and users. Anoyone else have the same error?

Thx in advance

**Comment by pingunaut** [comment] 2018-02-01 13:27
Rerpoducible

**Comment by pingunaut** [comment] 2018-02-01 14:49
Hi @dario-rodriguez I was able to reproduce the error. In my environment, it was caused by a Crowd HTTP compression issue.
Could you please try to disable Crowd HTTP compression like described here:
https://confluence.atlassian.com/crowdkb/how-to-disable-http-compression-on-crowd-2-9-and-above-856714638.html

**Comment by pingunaut** [comment] 2018-03-20 12:51
@dario-rodriguez this issue will be closed by the end of march if no feedback provided

**Closed** 2018-04-03 14:45 UTC
Labels: bug, waiting for feedback
