### ISSUE TITLE
Error in log about crowd plugin

### ISSUE THREAD

**Issue by shen3lu4** [pingunaut/nexus3-crowd-plugin#52] opened 2018-04-10 18:28 UTC
Nexus version: OSS 3.8.0-02
Crowd plugin version: nexus3-crowd-plugin-3.3.0.jar 
OS: Oracle Enterprise Linux 7.4

Set up Crowd integration per README and restarted nexus.

In nexus.log I see the following errors:
2018-04-10 14:21:00,721-0400 ERROR [qtp198972599-39]  *UNKNOWN com.pingunaut.nexus3.crowd.plugin.internal.entity.mapper.CrowdMapper - Error with request org.apache.http.client.entity.DecompressingEntity@7a9cf5b9 - 404
2018-04-10 14:21:00,738-0400 ERROR [pool-16-thread-4]  anonymous com.pingunaut.nexus3.crowd.plugin.internal.entity.mapper.CrowdMapper - Error with request org.apache.http.client.entity.DecompressingEntity@26d0af1e - 404
2018-04-10 14:23:02,001-0400 ERROR [qtp198972599-41]  *UNKNOWN com.pingunaut.nexus3.crowd.plugin.internal.entity.mapper.CrowdMapper - Error with request org.apache.http.client.entity.DecompressingEntity@9f7bffa - 404

In application -> Roles -> Create Role -> in Mapped Role drop down I only see a small subset of all roles available.

Any help would be appreciated!

**Comment by pingunaut** [comment] 2018-04-10 20:50
Hi @shen3lu4,
nexus3-crowd-plugin-3.4.0 is built for Nexus OSS 3.9.0.
For Nexus OSS 3.9.0 please try nexus3-crowd-plugin-3.3.0.

Please be aware that  nexus3-crowd-plugin-3.3.0 does not support JIRA as a user source, but only standalone Crowd. If you require embedded Crowd support with Nexus 3.8.0, please leave a comment here, I'll backport the feature then.

**Comment by shen3lu4** [comment] 2018-04-10 21:08
Sorry nexus3-crowd-plugin-3.4.0.jar is a typo. I am using nexus3-crowd-plugin-3.3.0.jar. Updated my original post.
Our Crowd is standalone, not embedded in JIRA. What could've the cause of the error I see?

**Comment by pingunaut** [comment] 2018-04-10 21:29
Alright thanks for the quick feedback. Unfortunatelly I'm not able to reproduce the issue although I tested with the weirdest group names... I'll provide an update with extended logging so the degugging will be easier. Might take a day or two...

**Comment by shen3lu4** [comment] 2018-04-10 21:52
Thanks for your quick response. FYI - Despite the error and not being able to see the full list from Crowd, I can still type in the Crowd group name in Mapped Role field and set it up successfully.

**Comment by pingunaut** [comment] 2018-07-02 16:07
@shen3lu4 the latest release (https://github.com/pingunaut/nexus3-crowd-plugin/releases/tag/nexus3-crowd-plugin-3.4.2) will log the complete http response if an error occurs. Maybe you could give it a try?

**Comment by shen3lu4** [comment] 2018-07-03 15:44
Upgraded nexus to OSS 3.12.1-01 and installed new plugin nexus3-crowd-plugin-3.4.2. I don't see the same error I saw before. But in the role mapping (Create role -> external role mapping -> select Crowd), in the "Role name" field I still only see a small subset of all roles in the drop down. But if I just type the role I need and set up the access, it actually works.

**Comment by pingunaut** [comment] 2019-02-13 16:49
If still relevant, please check [nexus3-crowd-plugin-3.6.0](https://github.com/pingunaut/nexus3-crowd-plugin/releases/tag/nexus3-crowd-plugin-3.6.0) which comes with support for large groups.
Closing this issue right now.
If problem persists, please reopen. Thanks a lot

**Closed by pingunaut** 2019-02-13 16:49 UTC
Labels: bug
