### ISSUE TITLE
plugin v3.6.2 not working with nexus v3.16.0

### ISSUE THREAD

**Issue by mrmunch** [pingunaut/nexus3-crowd-plugin#75] opened 2019-04-15 09:27 UTC
I updated an existing Nexus instance to version 3.16.0 and this plugin from version 3.4.2 to 3.6.2.
After Nexus started, I got this error (on the UI) when I tried to login with my Crowd credentials:
`Incorrect username or password, or no permission to use the application.`
After I downgraded plugin to previous version (3.4.2), login succeeded again.

For the error case (with v3.6.2) I found this in the karaf.log:
```
SEVERE: Could not launch framework
java.lang.RuntimeException: Error installing bundle listed in startup.properties with url: reference:file:nexus3-crowd-plugin-3.3.0.jar and startlevel: 200
        at org.apache.karaf.main.Main.installAndStartBundles(Main.java:495)
        at org.apache.karaf.main.Main.launch(Main.java:311)
        at org.sonatype.nexus.karaf.NexusMain.launch(NexusMain.java:106)
        at org.sonatype.nexus.karaf.NexusMain.main(NexusMain.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
        at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:60)
Caused by: java.lang.RuntimeException: Could not resolve nexus3-crowd-plugin-3.3.0.jar
        at org.apache.karaf.main.util.SimpleMavenResolver.resolve(SimpleMavenResolver.java:59)
        at org.apache.karaf.main.Main.installAndStartBundles(Main.java:483)
        ... 9 more
```

But I referenced nexus3-crowd-plugin-3.6.2 in my startup.properties:
`reference\:file\:nexus3-crowd-plugin-3.6.2.jar = 200`

**Comment by pingunaut** [comment] 2019-04-15 10:40
PLease check if [Version 3.7.0](https://github.com/pingunaut/nexus3-crowd-plugin/releases/tag/nexus3-crowd-plugin-3.7.0) solves your problem

**Comment by mrmunch** [comment] 2019-04-15 11:31
Please ignore the error message above, that was just an old entry.

Sadly, v3.7.0 leads to the same issue.

Note: Login succeeds also with v3.5.0

**Comment by webtomyfd** [comment] 2019-04-24 12:05
hi pingunaut,
bug confirmed same problem here. nexus-3.16.1-02 does not work with 
nexus3-crowd-plugin-3.7.0.jar and nexus3-crowd-plugin-3.7.1-SNAPSHOT.jar.

But it works with nexus3-crowd-plugin-3.5.0.jar

thanks and no big problem so far ;-)

thomas

**Comment by tobilarscheid** [comment] 2019-05-02 17:36
Hi Martin,

nexus-3.16 broke our plugin as well. Maybe this thread can serve as inspiration for you guys: https://github.com/larscheid-schmitzhermes/nexus3-github-oauth-plugin/issues/33

**Comment by pingunaut** [comment] 2019-05-02 20:56
@mrmunch do you have the chance to update to Nexus OSS 3.16.1 and give https://github.com/pingunaut/nexus3-crowd-plugin/releases/tag/nexus3-crowd-plugin-3.7.1 a try?
Problem seems to be fixed in my environment (without having done any update to the actual code...)

**Comment by mrmunch** [comment] 2019-05-06 11:05
Hi @pingunaut , sadly, I get the same error again :-(

**Comment by pingunaut** [comment] 2019-07-24 20:55
@mrmunch seems like plugin version 3.7.1 works fine with latest Nexus OSS 3.17.0 (#80 )
Do you have the possibility to check this and give a short feedback?

**Comment by mrmunch** [comment] 2019-07-25 13:29
Does not work for me :-(

Nexus: 3.170.
Plugin: 3.7.1
Crowd: 3.4.3

**Comment by webtomyfd** [comment] 2019-07-30 08:39
Hi @pingunaut 

same here, only Plugin 3.5.0 works. 3.6.x and above does not

Nexus: 3.17.0, 3.18.0
Crowd: 3.4.5

nexus.log
2019-07-30 10:36:28,738+0200 INFO  [FelixStartLevel]  *SYSTEM org.sonatype.nexus.security.internal.RealmManagerImpl - Loaded configuration: RealmConfiguration{realmNames=[NexusAuthenticatingRealm, NexusAuthorizingRealm, com.pingunaut.nexus3.crowd.plugin.CrowdAuthenticatingRealm]}
2019-07-30 10:36:28,745+0200 ERROR [FelixStartLevel]  *SYSTEM org.sonatype.nexus.security.internal.RealmManagerImpl - Unable to lookup security realms
java.lang.ClassNotFoundException: com.pingunaut.nexus3.crowd.plugin.CrowdAuthenticatingRealm

**Comment by mrmunch** [comment] 2019-08-04 10:59
Still failing with:

Nexus: 3.18.0
Plugin: 3.7.1
Crowd: 3.5.0

But plugin version 3.5.0 still works fine.

**Comment by jonesbusy** [comment] 2019-10-02 13:32
Hi,

What is the status about this issue ? 

I didn't had time to check again after 3.15 and version 3.5.0 of the plugin.

We would like to move to 3.19 (released yesterday), and were wondering about the status of this issue.

Thanks in advance!

**Comment by pingunaut** [comment] 2019-10-02 18:55
3.5.0 does still work. It's downside is that it is incompatible with npm token realm.
If npm token realm is not used, 3.5.0 should be fine. I no longer have access to a nexus/crowd environment, so I am very have to find contributors/successors to do future changes/fixes/PRs

**Comment by mrmunch** [comment] 2019-11-08 13:32
Hi @pingunaut ,
I created a script to build with all commits between v3.5.0 and v3.6.0 and test login - to find out where exactly it stopped working.
I found out, after [this commit](https://github.com/pingunaut/nexus3-crowd-plugin/commit/352635e16334d06ba8c40a71ab6f53825136d6c8) the login fails.

**Closed** 2020-01-21 11:52 UTC
Labels: bug
